// Copyright 2020 PerceptiSys Ltd, (Stephen Gaito)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This code has been inspired by: Shane Utt's excellent article:
//   https://shaneutt.com/blog/golang-ca-and-signed-cert-go/

package main

import (
  "os"
  "strings"
  "text/template"
)

func writeUserConfiguration(user User, defaults User, primaryUrl string) {

  user.Primary_Url = primaryUrl

  if user.Ca_Cert_Path == "" { user.Ca_Cert_Path = defaults.Ca_Cert_Path }
  if user.Cert_Path    == "" { user.Cert_Path    = defaults.Cert_Path }
  if user.Key_Path     == "" { user.Key_Path     = defaults.Key_Path }

  nPathPrefix := "users/"+user.Name +"/"+strings.ReplaceAll(user.Name, ".", "-")

  if user.Ca_Cert_Path == "" { user.Ca_Cert_Path = nPathPrefix+"-ca-crt.pem" }
  if user.Cert_Path    == "" { user.Cert_Path    = nPathPrefix+"-crt.pem" }
  if user.Key_Path     == "" { user.Key_Path     = nPathPrefix+"-key.pem" }
  if user.Config_Path  == "" { user.Config_Path  = nPathPrefix+"-config.yaml" }

  yamlTemplateStr := `
# This is the configuration for the {{.Name}} User
#
# It has been automatically generated by the cnSetup tool
#
# DO NOT EDIT THIS FILE (any changes will be lost)

name:         "{{.Name}}"
primary_url:  "{{.Primary_Url}}"
ca_cert_path: "{{.Ca_Cert_Path}}"
cert_path:    "{{.Cert_Path}}"
key_path:     "{{.Key_Path}}"
`
  yamlTemplate, err := template.New("yamlTemplate").Parse(yamlTemplateStr)
  setupMayBeFatal("Could not parse the yaml template", err)

  yamlFile, err := os.Create(user.Config_Path)
  setupMayBeFatal("Could not open the config file for writing", err)

  err = yamlTemplate.Execute(yamlFile, user)

  err = yamlFile.Close()
  setupMayBeFatal("Could not close the config file", err)
}
