#!/bin/bash

# This bash script copies the (static) browser application files from the 
# current directory. 

export srcDir=$(dirname $0)
export destDir=$(pwd)

echo "copying browser application files"
echo "  from $(basename $srcDir)"
echo "  to   $(basename $destDir)"

mkdir -p $destDir/browserApp

cp -Rvu $srcDir/browserApp $destDir

echo "------------------------------------------------------------------"
